/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oop_class.jufin;

import java.awt.Color;
import javax.swing.*;
import javax.swing.table.TableColumn;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.PreparedStatement;

/**
 *
 * @author Akbar
 */
public class jufin_main extends javax.swing.JFrame {
    public JComboBox<month> monthComboBox = new JComboBox<>(month.values());
    private DefaultTableModel dbModel;
    
    /**
     * Creates new form jufin_main
     */
    public jufin_main() {
        initComponents();
        
        // Define dbModel
        dbModel = new DefaultTableModel();
        
        // set dbTable settings to dbModel and declare columns
        dbTable.setModel(dbModel);
        dbModel.addColumn("ID");
        dbModel.addColumn("Judul");
        dbModel.addColumn("Bulan");
        
        loadData();
    }
    
    // Fungsi ini memuat data dari database (db_jufin) ke tabel (var dbTabel)
    public void loadData() {
        // Menghapus data
        dbModel.getDataVector().removeAllElements();
        
        // Info bahwa data telah kosong
        dbModel.fireTableDataChanged();
        
        try {
            Connection DB = DBConnect.getConnect();
            Statement STATE = DB.createStatement();
            String QUERY = "SELECT * FROM view_journals";
            ResultSet SET = STATE.executeQuery(QUERY);
            while(SET.next()){
                // lakukan penelusuran baris
                Object[] obj = new Object[3];
                obj[0] = SET.getString("journal_id");
                obj[1] = SET.getString("journal_name");
                obj[2] = SET.getString("month_name");
                dbModel.addRow(obj);
            }

            SET.close();
            STATE.close();
            
        } catch(SQLException e) {
                System.out.println("Terjadi Error di loadData)()");
        }
    }
    
    public void run_jurnalPage() {
        JFrame jPage = new jufin_jurnal();
        jPage.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        jPage.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        subtitleBuatJurnal = new javax.swing.JLabel();
        panelBuatJurnal = new javax.swing.JPanel();
        labelJudulJurnal = new javax.swing.JLabel();
        labelBulan = new javax.swing.JLabel();
        comboBulan = new javax.swing.JComboBox<>();
        fieldJudulJurnal = new javax.swing.JTextField();
        labelDeskripsi = new javax.swing.JLabel();
        fieldDeskripsi = new javax.swing.JTextField();
        btnTambahJurnal = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        panelDatabase = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dbTable = new javax.swing.JTable();
        labelDeskripsi1 = new javax.swing.JLabel();
        btnBukaJurnal = new javax.swing.JButton();
        btnLaporan = new javax.swing.JButton();
        btnHapusFDB = new javax.swing.JButton();
        fieldJudulJurnal1 = new javax.swing.JTextField();
        subtitleBuatJurnal1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        title.setFont(new java.awt.Font("Cascadia Mono", 1, 18)); // NOI18N
        title.setText("JUFIN");

        subtitleBuatJurnal.setFont(new java.awt.Font("Cascadia Mono", 1, 14)); // NOI18N
        subtitleBuatJurnal.setText("Buat Jurnal");

        panelBuatJurnal.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelJudulJurnal.setText("Judul");
        labelJudulJurnal.setToolTipText("");

        labelBulan.setText("Bulan");

        comboBulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "JANUARY", "FEBRUARY", "MARCH", "APRIL", "MAY", "JUNE", "JULY", "AUGUST", "SEPTEMBER", "OCTOBER", "NOVEMBER", "DECEMBER" }));
        comboBulan.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        fieldJudulJurnal.setToolTipText("Nama dari jurnal yang ingin dibuat");
        fieldJudulJurnal.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelDeskripsi.setText("Deskripsi");

        fieldDeskripsi.setToolTipText("Nama dari jurnal yang ingin dibuat");
        fieldDeskripsi.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        fieldDeskripsi.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        btnTambahJurnal.setText("Tambahkan");
        btnTambahJurnal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahJurnalActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBuatJurnalLayout = new javax.swing.GroupLayout(panelBuatJurnal);
        panelBuatJurnal.setLayout(panelBuatJurnalLayout);
        panelBuatJurnalLayout.setHorizontalGroup(
            panelBuatJurnalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuatJurnalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBuatJurnalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBuatJurnalLayout.createSequentialGroup()
                        .addComponent(labelJudulJurnal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldJudulJurnal))
                    .addGroup(panelBuatJurnalLayout.createSequentialGroup()
                        .addGroup(panelBuatJurnalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelBuatJurnalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(fieldDeskripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelDeskripsi, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(panelBuatJurnalLayout.createSequentialGroup()
                                .addComponent(btnTambahJurnal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnReset))
                            .addGroup(panelBuatJurnalLayout.createSequentialGroup()
                                .addComponent(labelBulan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboBulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 10, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelBuatJurnalLayout.setVerticalGroup(
            panelBuatJurnalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuatJurnalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBuatJurnalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelJudulJurnal)
                    .addComponent(fieldJudulJurnal, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBuatJurnalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBulan)
                    .addComponent(comboBulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelDeskripsi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldDeskripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBuatJurnalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambahJurnal)
                    .addComponent(btnReset))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        panelDatabase.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        dbTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Judul", "Bulan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(dbTable);

        labelDeskripsi1.setText("Selected");

        btnBukaJurnal.setText("Buka");
        btnBukaJurnal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBukaJurnalActionPerformed(evt);
            }
        });

        btnLaporan.setText("Laporan");
        btnLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaporanActionPerformed(evt);
            }
        });

        btnHapusFDB.setBackground(new java.awt.Color(255, 51, 51));
        btnHapusFDB.setForeground(new java.awt.Color(255, 255, 255));
        btnHapusFDB.setText("Hapus");
        btnHapusFDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusFDBActionPerformed(evt);
            }
        });

        fieldJudulJurnal1.setEditable(false);
        fieldJudulJurnal1.setBackground(new java.awt.Color(204, 204, 255));
        fieldJudulJurnal1.setToolTipText("Nama dari jurnal yang ingin dibuat");
        fieldJudulJurnal1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout panelDatabaseLayout = new javax.swing.GroupLayout(panelDatabase);
        panelDatabase.setLayout(panelDatabaseLayout);
        panelDatabaseLayout.setHorizontalGroup(
            panelDatabaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatabaseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDatabaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDatabaseLayout.createSequentialGroup()
                        .addComponent(labelDeskripsi1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldJudulJurnal1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBukaJurnal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLaporan)
                        .addGap(88, 88, 88)
                        .addComponent(btnHapusFDB))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDatabaseLayout.setVerticalGroup(
            panelDatabaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDatabaseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDatabaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDeskripsi1)
                    .addComponent(btnBukaJurnal)
                    .addComponent(btnLaporan)
                    .addComponent(btnHapusFDB)
                    .addComponent(fieldJudulJurnal1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        subtitleBuatJurnal1.setFont(new java.awt.Font("Cascadia Mono", 1, 14)); // NOI18N
        subtitleBuatJurnal1.setText("Database");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(subtitleBuatJurnal)
                        .addGap(183, 183, 183)
                        .addComponent(subtitleBuatJurnal1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelBuatJurnal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelDatabase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(title)
                .addGap(349, 349, 349))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subtitleBuatJurnal)
                    .addComponent(subtitleBuatJurnal1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelBuatJurnal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelDatabase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Tombol untuk menambahkan jurnal ke database
    private void btnTambahJurnalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahJurnalActionPerformed
        String judul = fieldJudulJurnal.getText();
        int selectedBulan = comboBulan.getSelectedIndex();
        String deskripsi = fieldDeskripsi.getText();
        
        try {
            Connection DB = DBConnect.getConnect();
            String QUERY = "INSERT INTO journals VALUES(?, ?, ?, ?)";
            PreparedStatement STATE = DB.prepareStatement(QUERY);
            STATE.setString(1, "DEFAULT");
            STATE.setString(2, judul);
            STATE.setString(3, deskripsi);
            STATE.setInt(4, selectedBulan);
            STATE.executeUpdate();
            STATE.close();
        } catch (SQLException e) {
            System.out.println("Terjadi Error di TambahAction");
        } finally {
            loadData();
        }
    }//GEN-LAST:event_btnTambahJurnalActionPerformed

    // Kosongi seluruh field pada panelBuatJurnal
    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaporanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLaporanActionPerformed

    private void btnHapusFDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusFDBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHapusFDBActionPerformed

    private void btnBukaJurnalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBukaJurnalActionPerformed
        run_jurnalPage();
    }//GEN-LAST:event_btnBukaJurnalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jufin_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jufin_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jufin_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jufin_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jufin_main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBukaJurnal;
    private javax.swing.JButton btnHapusFDB;
    private javax.swing.JButton btnLaporan;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTambahJurnal;
    private javax.swing.JComboBox<String> comboBulan;
    private javax.swing.JTable dbTable;
    private javax.swing.JTextField fieldDeskripsi;
    private javax.swing.JTextField fieldJudulJurnal;
    private javax.swing.JTextField fieldJudulJurnal1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelBulan;
    private javax.swing.JLabel labelDeskripsi;
    private javax.swing.JLabel labelDeskripsi1;
    private javax.swing.JLabel labelJudulJurnal;
    private javax.swing.JPanel panelBuatJurnal;
    private javax.swing.JPanel panelDatabase;
    private javax.swing.JLabel subtitleBuatJurnal;
    private javax.swing.JLabel subtitleBuatJurnal1;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
